version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions once a week on Monday
      interval: "weekly"
      day: "monday"
